//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.h
//  @ Date : 10.03.2026
//  @ Author : 
//
//


#if !defined(_PIES_H)
#define _PIES_H

#include "Ssak.h"

class Pies : public Ssak {
public:
	void szczekanie();
	void aportowanie();
	void daj_lape();
	void siad();
	Pies(char rasa, char imie, int wiek, Ssak ssak);
	Ssak(bool czy_zywy, char plec);
private:
	char rasa;
	char imie;
	int wiek;
};

#endif  //_PIES_H
