//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.cpp
//  @ Date : 10.03.2026
//  @ Author : 
//
//


#include "Pies.h"
#include "Ssak.h"

void Pies::szczekanie() {

}

void Pies::aportowanie() {

}

void Pies::daj_lape() {

}

void Pies::siad() {

}

Pies::Pies(char rasa, char imie, int wiek, Ssak ssak) {

}

Pies::Ssak(bool czy_zywy, char plec) {

}

