//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.cpp
//  @ Date : 10.03.2026
//  @ Author : 
//
//


#include "Ssak.h"

void Ssak::jedzenie() {

}

void Ssak::picie() {

}

void Ssak::spanie() {

}

Ssak::Ssak(bool czy_zywy, char plec) {

}

