//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.h
//  @ Date : 10.03.2026
//  @ Author : 
//
//


#if !defined(_SSAK_H)
#define _SSAK_H


class Ssak {
public:
	bool czy_zywy;
	void jedzenie();
	void picie();
	void spanie();
	Ssak(bool czy_zywy, char plec);
private:
	char plec;
};

#endif  //_SSAK_H
